### ISSUE TITLE
Nothing on the image viewer page and cannot apply filters as well

### ISSUE THREAD

**Issue by hiralatecf** [avniproject/avni-media#135]
I am not able to see any images nor am I able to apply filters.
RWB project.
Thank you.

**Comment by vinayvenu** [comment]
@hiralatecf There are some issues with running of ETL for the RWB organisations. Working on it now.

**Comment by himeshr** [comment]
We have fixed 2 things to get the Media-Viewer working to show few of the images:

1. Recreate ETL schema for rwbngos2023 and gdgsgom to fix change in conceptType error
2. Correct the app URLs used in Media-server for prod organisation

<img width="1840" alt="Screenshot 2023-07-07 at 2 37 09 PM" src="https://github.com/avniproject/avni-media/assets/72493481/da847314-f44d-405e-bd24-49214830c6ec">

**Comment by himeshr** [comment]
On Debugging the broken thumbnails issue, found that those were for video media content, which is not yet supported in Media-Viewer app.

Ex: "9ced444d-b29d-44e5-88e7-11e48cdd4351": "https://s3.ap-south-1.amazonaws.com/prod-user-media/rwbngos2023/0852a9c2-b03e-40f2-bd28-8a61a9bd5219.mp4"
0852a9c2-b03e-40f2-bd28-8a61a9bd5219 is a broken thumbnail, as its a mp4 file.
<img width="1840" alt="Screenshot 2023-07-07 at 3 12 51 PM" src="https://github.com/avniproject/avni-media/assets/72493481/1a7a6e93-9d6c-4735-b9a0-45e3a89ad217">

**Comment by hiralatecf** [comment]
I still cannot view any images..!!
is there anything that I am doing wrong?
The filter options are now open but I am not able to view the images - 0 images.

**Comment by hiralatecf** [comment]
I think rwb2023 is not working?

**Comment by himeshr** [comment]
Analytics (ETL) has been enabled only for following organisations:
"rwbniti", "rwbnitiuat", "gdgsgom" and "rwbmh"

It has been enabled for OrganisationGroup "rwb".

"HasAnalyticsDB" has to be enabled for "rwb2023" for MediaViewer to work for it as well.
Support team could help you get the analytics enabled for all your required organisations.

**Comment by hiralatecf** [comment]
Thank you Himesh.
But I am not able to see all the images in the rwbngos2023 organization.
Also filtering is not open for all subjects/encounters?
I want to see images in work order registration but I am not able to.

**Comment by himeshr** [comment]
> Thank you Himesh. But I am not able to see all the images in the rwbngos2023 organization. Also filtering is not open for all subjects/encounters? I want to see images in work order registration but I am not able to.

Hi Hiral, i've created a separate issue to track this valid concern.
https://github.com/avniproject/avni-media/issues/140
